import { StudentController } from "../controllers/studentController.js";
import express from "express";
const router=express.Router();
router.get('/',StudentController.getAllDocs);
router.post('/',StudentController.createDoc);
router.get('/getData',StudentController.getAllDocs1);
router.post('/addData',StudentController.createDoc1);
router.get('/edit/:id',StudentController.editDocs);
router.post('/update/:id',StudentController.updateDocsById);
router.post('/delete/:id',StudentController.deleteDocsById);
router.post('/updateData/:id',StudentController.updateDocsById1);
router.post('/deleteData/:id',StudentController.deleteDocsById1);
export default router;
